In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("retail_store_sales.csv")
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [3]:
df.shape

(12575, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.9+ MB

In [5]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.dtypes

Transaction ID          str
Customer ID             str
Category                str
Item                    str
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Discount Applied     object
dtype: object

In [9]:
df["Discount Applied"].value_counts(dropna=False)

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [10]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [11]:
df[["Item" ,"Price Per Unit","Quantity" ,"Total Spent"]].isnull().sum()

Item              1213
Price Per Unit     609
Quantity           604
Total Spent        604
dtype: int64

In [13]:
df[df["Item"].isna()][["Item","Price Per Unit" ,"Quantity" ,"Total Spent"]].head(10)

   Item  Price Per Unit  Quantity  Total Spent
5   NaN             NaN      10.0        200.0
7   NaN            33.5       NaN          NaN
11  NaN             NaN       8.0         52.0
15  NaN            24.5       NaN          NaN
17  NaN             NaN      10.0        275.0
19  NaN            35.0       NaN          NaN
21  NaN             NaN       3.0        105.0
25  NaN            39.5       NaN          NaN
32  NaN             NaN       8.0        196.0
34  NaN            23.0       NaN          NaN

In [14]:
df[df["Price Per Unit"].isna()][["Item","Price Per Unit" ,"Quantity","Total Spent"]].head(10)

    Item  Price Per Unit  Quantity  Total Spent
5    NaN             NaN      10.0        200.0
11   NaN             NaN       8.0         52.0
17   NaN             NaN      10.0        275.0
21   NaN             NaN       3.0        105.0
32   NaN             NaN       8.0        196.0
127  NaN             NaN      10.0        275.0
159  NaN             NaN       9.0        126.0
216  NaN             NaN       8.0         40.0
247  NaN             NaN       7.0        150.5
271  NaN             NaN       9.0         99.0

In [16]:
df[df["Quantity"].isna()][["Item","Price Per Unit","Quantity","Total Spent"]].head(10)

    Item  Price Per Unit  Quantity  Total Spent
7    NaN            33.5       NaN          NaN
15   NaN            24.5       NaN          NaN
19   NaN            35.0       NaN          NaN
25   NaN            39.5       NaN          NaN
34   NaN            23.0       NaN          NaN
83   NaN            15.5       NaN          NaN
112  NaN            20.0       NaN          NaN
114  NaN            39.5       NaN          NaN
118  NaN            27.5       NaN          NaN
138  NaN            35.0       NaN          NaN

In [17]:
df[df["Total Spent"].isna()][["Item" ,"Price Per Unit" ,"Quantity","Total Spent"]].head(15)

    Item  Price Per Unit  Quantity  Total Spent
7    NaN            33.5       NaN          NaN
15   NaN            24.5       NaN          NaN
19   NaN            35.0       NaN          NaN
25   NaN            39.5       NaN          NaN
34   NaN            23.0       NaN          NaN
83   NaN            15.5       NaN          NaN
112  NaN            20.0       NaN          NaN
114  NaN            39.5       NaN          NaN
118  NaN            27.5       NaN          NaN
138  NaN            35.0       NaN          NaN
139  NaN            24.5       NaN          NaN
179  NaN            23.0       NaN          NaN
182  NaN             6.5       NaN          NaN
232  NaN            30.5       NaN          NaN
234  NaN            38.0       NaN          NaN

In [19]:
df["Item"] = df["Item"].fillna("Unknown")

In [20]:
df["Price Per Unit"] = df["Price Per Unit"].fillna(df["Price Per Unit"].median())
df["Quantity"]= df["Quantity"].fillna(df["Quantity"].median())
df["Total Spent"] = df["Total Spent"].fillna(df["Total Spent"].median())
df["Discount Applied"]= df["Discount Applied"].fillna("Unknown")

In [21]:
df["Transaction Date"]= pd.to_datetime(df["Transaction Date"])

In [23]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Category            0
Item                0
Price Per Unit      0
Quantity            0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Discount Applied    0
dtype: int64

In [24]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,Unknown
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              12575 non-null  str
 4   Price Per Unit    12575 non-null  float64
 5   Quantity          12575 non-null  float64
 6   Total Spent       12575 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  12575 non-null  object
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.8+ MB

In [26]:
df.to_csv("retail_store_sales_cleaned.csv",index=False)

# Task 1: Data Cleaning

## Dataset
Retail Store Sales Dataset

## Cleaning Steps Performed

1. Checked the dataset dimensions and data types.
2. Checked for missing values.
3. Checked for duplicate records.
4. Handled missing values in the `Item` column by replacing them with `Unknown`.
5. Handled missing numerical values in `Price Per Unit`, `Quantity`, and `Total Spent` using the median.
6. Handled missing values in `Discount Applied` by replacing them with `Unknown`.
7. Converted `Transaction Date` from text format to datetime format.
8. Verified the cleaned dataset to ensure there were no remaining missing values.
9. Saved the cleaned dataset as `retail_store_sales_cleaned.csv`.

## Duplicate Check
Number of duplicate rows found: 0

## Output
The cleaned dataset was saved as:

`retail_store_sales_cleaned.csv`